# Generated by Django 4.2.7 on 2024-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_song_artist_alter_song_avatar_alter_song_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='song',
        ),
        migrations.AddField(
            model_name='room',
            name='songs',
            field=models.ManyToManyField(null=True, to='base.song'),
        ),
    ]
