# Generated by Django 4.2.7 on 2024-01-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_room_songs_room_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='song',
            new_name='songs',
        ),
    ]
